const AUTH_REQUEST = {
    REQUEST_CURRENT_USER:'REQUEST_CURRENT_USER',
    REQUEST_CONFIRM : 'REQUEST_CONFIRM',
    REQUEST_SIGN_IN : 'REQUEST_SIGN_IN',
    REQUEST_SIGN_UP : 'REQUEST_SIGN_UP',
    REQUEST_SIGN_OUT : 'REQUEST_SIGN_OUT'
};
const AUTH_PROCEED = {
    SIGN_IN_PROCEED : 'SIGN_IN_PROCEED',
    SIGN_OUT_PROCEEED: 'SIGN_OUT_PROCEED'
}
const API_REQUEST = {
    CREATE_DOC: 'CREATE_DOC',
    GET_DOC: 'GET_DOC',
    UPDATE_DOC : 'UPDATE_DOC',
    DELECT_DOC : 'DELETE_DOC',
    QUERY_DOCS: 'QUERY_DOCS',
    CREATE_NEW_SHORTEN_URL : 'CREATE_NEW_SHORTEN_URL',
    QUERY_SHORTEN_URLS: 'QUERY_SHORTEN_URLS'
}
const API_PROCEED = {
    CREATE_PROCEED: 'CREATE_PROCEED',
    UPLOAD_PROCEED : 'UPLOAD_PROCEED',
    QUERY_PROCEED : 'QUERY_PROCEED'
}
const DOC_CONTROL = {
    SET_DOC_REQUEST: 'SET_DOC_REQUEST',
    SET_DOC : 'SET_DOC',
    SET_CONTENT: 'SET_CONTENT',
    SET_TITLE: 'SET_TITLE'
}
const FORM_CONTROL = {
    SET_FORM_VALUE: 'SET_FORM_VALUE',
    CLEAR_FORM_VALUE: 'CLEAR_FORM_VALUE'
}
const TOAST_CONTROL = {
    TOAST_ON : 'TOAST_ON',
    TOAST_OFF : 'TOAST_OFF'
}
export default {
    AUTH_REQUEST,
    AUTH_PROCEED,
    API_REQUEST,
    API_PROCEED,
    DOC_CONTROL,
    FORM_CONTROL,
    TOAST_CONTROL
};